version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fasho-server-dc
    container_name: fasho-node-server-dc
    command: npm run server
    ports:
      - "5000:5000"
    depends_on:
      - redisdb
    networks:
      - app-network

  # client:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: fasho-client-dc
  #   container_name: fasho-node-client-dc
  #   command: npm run start
  #   depends_on:
  #     - server
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network

  redisdb:
    image: 'redis:alpine'
    restart: always
    hostname: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

networks:
    app-network:
        driver: bridge