openapi: 3.0.0
info:
  title: Fasho API
  description: Optional multiline
  version: 0.1.9
servers:
  - url: http://localhost:5000/
    description: This is the main Development server
  - url: http://localhost:3000/
    description: This is the main Front-end Development server
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
paths:
  /api/orders/products:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /api/orders/{id}:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
          type: 
          format: 
      responses:
        "201":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  

      responses:
        "201":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  
  /api/orders/myorders:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/orders/:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/orders/:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/products/:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/users/:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  
  /api/users/profile:
    get:
      summary: Returns a list of orders.
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  # /api/users/login:
  #   post:
  #     summary: Returns a list of orders.
  #     description: Optional extended description in CommonMark or HTML
  #     responses:
  #       "200":
  #         description: A JSON array of user names
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: string